// <auto-generated />
using MVCSQLServer.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MVCSQLServer.Migrations
{
    [DbContext(typeof(ContextDatabase))]
    [Migration("20221216021750_GamesList-Creation")]
    partial class GamesListCreation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MVCSQLServer.Models.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("category");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "MMORPG"
                        },
                        new
                        {
                            Id = 2,
                            Name = "First Person Shooter"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Simulation"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Moba"
                        });
                });

            modelBuilder.Entity("MVCSQLServer.Models.Entities.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("CategoryId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("games");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Name = "World of Warcraft"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Name = "Final Fantasy XIV"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Name = "CS:GO"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Name = "Overwatch"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            Name = "The Sims 4"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            Name = "Stardew Valley"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 4,
                            Name = "League of Legends"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 4,
                            Name = "Dota 2"
                        });
                });

            modelBuilder.Entity("MVCSQLServer.Models.Entities.Game", b =>
                {
                    b.HasOne("MVCSQLServer.Models.Entities.Category", "Category")
                        .WithMany("Games")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MVCSQLServer.Models.Entities.Category", b =>
                {
                    b.Navigation("Games");
                });
#pragma warning restore 612, 618
        }
    }
}
